### ISSUE TITLE
Models that did not convert

### ISSUE THREAD

**Issue by 09williamsad** [KillzXGaming/NTT-Model-Dumper#1]
I ran the tool with all the models in batch, 177 of them did not export a dae file.
See this list for those that did not convert.
[LSWUnconverted.txt](https://github.com/KillzXGaming/NTT-Model-Dumper/files/8500601/LSWUnconverted.txt)

i.e.
`ModelDumper.exe SR_TALLSTRAIGHT_SCRAPER_DX11.MODEL
Unhandled exception. System.Exception: Invalid signature`

`ModelDumper.exe DEATHSTAR_TURRETS_TOP_DX11.MODEL
Unhandled exception. System.Exception: Unknown index format! 4
   at TTLibrary.Model.ParseCSG(FileReader reader) in C:\Users\Nathan\Documents\GitHub\MapStudioRewrite\TTLibrary\Model.cs:line 86
   at TTLibrary.Model.ParseChunk(FileReader reader, ResourceChunk chunk) in C:\Users\Nathan\Documents\GitHub\MapStudioRewrite\TTLibrary\Model.cs:line 50
   at TTLibrary.Model.Read(FileReader reader) in C:\Users\Nathan\Documents\GitHub\MapStudioRewrite\TTLibrary\Model.cs:line 35
   at TTLibrary.Model..ctor(String filePath) in C:\Users\Nathan\Documents\GitHub\MapStudioRewrite\TTLibrary\Model.cs:line 25
   at TTLibrary.Program.Main(String[] args) in C:\Users\Nathan\Documents\GitHub\MapStudioRewrite\TTLibrary\Program.cs:line 19`
[LSWExamples.zip](https://github.com/KillzXGaming/NTT-Model-Dumper/files/8500607/LSWExamples.zip)

**Comment by KillzXGaming** [comment]
Fixed the index 4 error.

![image](https://user-images.githubusercontent.com/13475262/163695230-cfdcdb0a-1cfa-4b02-b786-a1abd9cb7b2d.png)

Still a few that error out atm. Might be failing to read something correctly. 

Edit seems there is a section after indices which I am not sure how it is structured.

Also there is a separate node section at the bottom of everything which may be important for mesh names and transforms.

**Comment by KillzXGaming** [comment]
They should all dump now as of https://github.com/KillzXGaming/NTT-Model-Dumper/commit/c4f8749d5a20c0347b299f822d486322886818b3 unless there is some additional bugs.
